name: Ubuntu CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: ubuntu-latest
            
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Create Conda Environment
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda env update --file environment.yml --name base
    - name: Activate ipt environment
      run: |
         $CONDA/bin/conda activate ipt
        
    - name: Install Image Processing Tools
      run: |
        $CONDA/bin/python setup.py develop --user
    - name: Test with pytest
      run: |
            $CONDA/bin/python -m pytest
